### ISSUE TITLE
Woopra ID / Email Issue

### ISSUE THREAD

**Issue by sperand-io** [segment-integrations/integration-woopra#1]
Let's sync with their team on best practices and how to move forward. 

https://www.woopra.com/docs/developer/http-tracking-api/

>The request property “id” has been deprecated. Woopra will merge visitors only by the visitor’s email property (cv_email) .

^^^We send and rely on that `id` parameter right now!

**Comment by hankim813** [comment]
Closed for inactivity/irrelevance. Please reopen if it's still an issue!
